### ISSUE TITLE
About finaldataset

### ISSUE THREAD

**Issue by yongrenr** [f-kretschmer/bertax_training#14]
Hello! I'm very interested in your work! I would like to try your model's performance on the final dataset.
I used final_model_dataset directly and processed them into json and txt files.But he always asks me to pass in virus.dataset,what should i do?
Thank u!!!!

**Use Bash Code:**
          python -m models.bert_nc_finetune bert_nc_C2_final.h5  /home/dataset/final_model_dataset \
              --multi_tax \
              --epochs 15 \
              --batch_size 128 \
              --save_name _small_trainingset_filtered_fix_classes_selection \
              --store_predictions \
              --nr_seqs 1000000000

**Traceback (most recent call last):**
  File "/root/miniconda3/envs/bertax_37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/bertax_37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bertax_training-master/models/bert_nc_finetune.py", line 320, in <module>
    x, y, y_species = load_fragments(args.fragments_dir, balance=False, nr_seqs=args.nr_seqs)
  File "/home/bertax_training-master/models/bert_nc_finetune.py", line 44, in load_fragments
    fragments_dir, f'{class_}_fragments.json')))))
FileNotFoundError: [Errno 2] No such file or directory: '/home/dataset/final_model_dataset/Viruses_fragments.json'

**Comment by yongrenr** [comment]
Do you have a final classification model? And how do I run him?
We look forward to hearing from you!！！！！！！

**Comment by yongrenr** [comment]
Hi！I studied your work again. I want to use the "big_trainingset_all_fix_classes_selection.h5" model on the “test data” pair to see how well the test classification works. But there's a problem. What do I need to do?
My dataset directory (/home/dataset/final_model_dataset) look this:
![image](https://github.com/f-kretschmer/bertax_training/assets/78602328/7bc1ab03-adf4-4478-b076-28b6a0300a3e)
![image](https://github.com/f-kretschmer/bertax_training/assets/78602328/94f427ff-2fa5-478f-8577-edcbdf25d9da)
![image](https://github.com/f-kretschmer/bertax_training/assets/78602328/6daf7a69-0442-487f-973d-e057c3f5407a)
![image](https://github.com/f-kretschmer/bertax_training/assets/78602328/ba6855b7-689c-49c8-9355-625356cf0b0f)

2.I seem to have found the model that will eventually be used to test classification
”big_trainingset_all_fix_classes_selection.h5“
Is that right？

Thank you very much!！！！

**Comment by f-kretschmer** [comment]
I'm not sure if I understand what you want to do: If you want to **run** the model, don't use the finetune-script but instead the scripts of the ["bertax" repository](https://github.com/f-kretschmer/bertax). If you want to **finetune** (so train) the model, your data has to be organized in the way I described. Your "test" directory is organized in the wrong way, it should look like the "final" directory, meaning each class ("final" does not make sense here) hast to have its sequences in the json file (e.g., `Viruses_fragments.json` for the class Viruses) and the taxonomic species IDs in the `_species_picked.txt` file (for Viruses: `Viruses_species_picked.txt`).

**Comment by yongrenr** [comment]
> I'm not sure if I understand what you want to do: If you want to **run** the model, don't use the finetune-script but instead the scripts of the ["bertax" repository](https://github.com/f-kretschmer/bertax). If you want to **finetune** (so train) the model, your data has to be organized in the way I described. Your "test" directory is organized in the wrong way, it should look like the "final" directory, meaning each class ("final" does not make sense here) hast to have its sequences in the json file (e.g., for the class Viruses) and the taxonomic species IDs in the file (for Viruses: ).`Viruses_fragments.json``_species_picked.txt``Viruses_species_picked.txt`

Thank u！！！！
