### ISSUE TITLE
pretrain data clarification

### ISSUE THREAD

**Issue by JiayiJennie** [f-kretschmer/bertax_training#15]
Hello! I want to reproduce your repo and found there are "final_model_data_seperate_fasta_per_superkingdom" and "pretraining_dataset" listed in your database. The latter is the subset of the first. Which one is used to pretrian in your paper? Thanks!
<img width="570" alt="Screenshot 2024-06-25 at 9 17 43 AM" src="https://github.com/rnajena/bertax_training/assets/91341826/9a7db00c-e5f1-43da-af8c-e9bbfab28602">

**Comment by f-kretschmer** [comment]
Hi, these two datasets should be just alternative versions of one-another. The pretraining dataset however is the `pretraining_dataset.zip` (`final_model_dataset.zip` was used for fine-tuning of the final model).
