### ISSUE TITLE
Is it possible to publish your version of Keras and TensorFlow？

### ISSUE THREAD

**Issue by LoadStar822** [f-kretschmer/bertax_training#8]
我在训练时出现错误：ValueError: Could not interpret optimizer identifier: <keras_bert.optimizers.warmup_v2.AdamWarmup object at 0x7f174ebcfe20>。
这可能是因为Keras、TensorFlow、Python的版本不同，您能公布一下版本吗，非常感谢！

**Comment by f-kretschmer** [comment]
For now, see https://github.com/f-kretschmer/bertax/blob/master/conda.recipe/meta.yaml.
